language: rust

matrix:
	fast_finish: true
	include:
		- rust: nightly-i686
			os: linux
			addons:
				apt:
					packages: &i686_unknown_linux_gnu
						- gcc-multilib
						- libssl:i386

script:
	- cargo build --verbose
