language: rust

matrix:
  fast_finish: true

  include:
    - rust: nightly-i686
      os: linux
      addons:
        apt:
          packages: &i686_unknown_linux_gnu
            # Cross compiler and cross compiled C libraries
            - gcc-multilib
            - libssl:i3

script:
  - cargo build --verbose
