environment:
  matrix:
    - TARGET: i686-pc-windows-msvc
      CHANNEL: nightly

install:
  - curl -sSf -o rustup-init.exe https://win.rustup.rs
  - rustup-init.exe --default-host %TARGET% --default-toolchain %CHANNEL% -y
  - set PATH=%PATH%;C:\Users\appveyor\.cargo\bin
  - rustc -Vv
  - cargo -V

matrix:
  fast_finish: true

build: false

test_script:
  - cargo build --verbose
